[package]
name = "test_gtk"
version = "0.1.0"
authors = ["fcvr"]

[dependencies]
lazy_static = "0.2.8"
pcap-file = "0.7.0"
gdk = "0.5.3"
rand = "0.3.15"
cast = "0.2.2"
rust-ini = "0.9"


[dependencies.gtk]
version = "0.1.3"
features = ["v3_10"]